### PR TITLE
Update

### PR DESCRIPTION
**Pull request by intika**
Use correct libjson-glib to correct this bug 
https://github.com/mikeage/prpltwtr/issues/26

### CODE REVIEW

**Comment by mikeage** [comment]
Thanks for your submission. Unfortunately, I don't use Windows anymore, and so I no longer use pidgin, and can't really test this. Feel free to fork and maintain your branch, but I can't really agree to merge this without testing it myself. As far as I'm concerned, this particular repo is dead :-/

**Comment by intika** [comment]
nice move :) 
i am planning to do so also but it takes new time to setup a new system etc... 
i am curious what solution do you use as alternative to pidgin ?

**Comment by mikeage** [comment]
https://sites.google.com/site/yorufukurou/ for twitter, adium for messaging

**Comment by intika** [comment]
thanks

**Pull request closed without merging**
